package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table(name = "attachment", catalog = "document")
public class Attachment implements java.io.Serializable {

	private static final long serialVersionUID = -2935648839076161772L;
	
	private Integer attachmentId;
	private String attachmentName;
	private Integer objectId;
	private String objectName;
	private String originalFileName;
	private String contentType;
	private byte[] content;

	public Attachment() {
	}

	public Attachment(String attachmentName, Integer objectId, String objectName,
			String originalFileName, String contentType, byte[] content) {
		this.attachmentName = attachmentName;
		this.objectId = objectId;
		this.objectName = objectName;
		this.originalFileName = originalFileName;
		this.contentType = contentType;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ATTACHMENT_ID", unique = true, nullable = false)  
	public Integer getAttachmentId() {
		return attachmentId;
	}
	
	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	@Column(name = "ATTACHMENT_NAME")
	public String getAttachmentName() {
		return attachmentName;
	}

	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName;
	}

	@Column(name = "OBJECT_ID")
	public Integer getObjectId() {
		return objectId;
	}

	public void setObjectId(Integer objectId) {
		this.objectId = objectId;
	}

	@Column(name = "OBJECT_NAME")
	public String getObjectName() {
		return objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@Column(name = "ORIGINAL_FILENAME")
	public String getOriginalFileName() {
		return originalFileName;
	}

	public void setOriginalFileName(String originalFileName) {
		this.originalFileName = originalFileName;
	}

	@Column(name = "CONTENT_TYPE")
	public String getContentType() {
		return contentType;
	}
	
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "CONTENT")
	public byte[] getContent() {
		return content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}


}
