package com.java.doc.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookReciveOut generated by hbm2java
 */
@Entity
@Table(name = "book_recieve_department", catalog = "document")
public class BookRecieveDepartment implements java.io.Serializable {

	private static final long serialVersionUID = 9064456693298707535L;
	private Integer brDepartmentId;
	private Integer brId;
	private String brToDepartment;
	private String brToDepartmentShort;
	private String brToDepartmentName;
	private String status;
	private String updatedBy;
	private Date updatedDate;
	private Integer runningNo;
	private String remark;
	
	public BookRecieveDepartment() {
	}

	@Override
	public String toString(){
		String str = " brId : " + brId + ", "
				+ " brDepartmentId : " + brDepartmentId + ", "
				+ " brToDepartment : " + brToDepartment + ", "
				+ " brToDepartmentShort : " + brToDepartmentShort + ", "
				+ " updatedBy : " + updatedBy + ", "
				+ " updatedDate : " + updatedDate + ", "
				+ " status : " + status
				+ " runningNo : " + runningNo;
		return str;
	}
	
	public BookRecieveDepartment(Integer brId, Integer brDepartmentId, String brToDepartment,
			String brToDepartmentShort, String brToDepartmentName, String status, String updatedBy, Date updatedDate) {
		this.brDepartmentId = brDepartmentId;
		this.brId = brId;
		this.brToDepartment = brToDepartment;
		this.brToDepartmentShort = brToDepartmentShort;
		this.brToDepartmentName = brToDepartmentName;
		this.status = status;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BR_TO_ID", unique = true, nullable = false)
	public Integer getBrDepartmentId() {
		return this.brDepartmentId;
	}

	public void setBrDepartmentId(Integer brToId) {
		this.brDepartmentId = brToId;
	}
	
	@Column(name = "BR_ID")
	public Integer getBrId() {
		return this.brId;
	}

	public void setBrId(Integer brId) {
		this.brId = brId;
	}

	@Column(name = "BR_TO_DEPARTMENT")
	public String getBrToDepartment() {
		return this.brToDepartment;
	}

	public void setBrToDepartment(String brToDepartment) {
		this.brToDepartment = brToDepartment;
	}
	
	@Column(name = "BR_TO_DEPARTMENT_NAME")
	public String getBrToDepartmentName() {
		return brToDepartmentName;
	}

	public void setBrToDepartmentName(String brToDepartmentName) {
		this.brToDepartmentName = brToDepartmentName;
	}

	@Column(name = "BR_TO_DEPARTMENT_SHORT")
	public String getBrToDepartmentShort() {
		return brToDepartmentShort;
	}

	public void setBrToDepartmentShort(String brToDepartmentShort) {
		this.brToDepartmentShort = brToDepartmentShort;
	}	
	
	@Column(name = "STATUS")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}	
	
	@Column(name = "UPDATED_BY")
	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}	
	
	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}	
	
	@Column(name = "RUNNING_NO")
	public Integer getRunningNo() {
		return runningNo;
	}

	public void setRunningNo(Integer runningNo) {
		this.runningNo = runningNo;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}	
	
	
}
