package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookReciveOut generated by hbm2java
 */
@Entity
@Table(name = "book_recive_out", catalog = "document")
public class BookReciveOut implements java.io.Serializable {

	private static final long serialVersionUID = -7691383831281035458L;
	private Integer brId;
	private Integer brNum;
	private Integer brYear;
	private Date brRdate;
	private Integer brTypeQuick;
	private Integer brTypeSecret;
	private String brPlace;
	private Date brDate;
	private String brFrom;
	private String brTo;
	private String brSubject;
	private String brRemark;
	private String brDivision;
	private String brPcode;
	private String brStatus;
	private String brImage;/*
	private integer typequick;
	private integer typesecret;*/
	private String createdBy;
	private Date createdDate;
	private String division;
	private String updatedBy;
	private Date updatedDate;
	
	public BookReciveOut() {
	}

	@Override
	public String toString(){
		String str = " brId : " + brId + ", "
				+ " brNum : " + brNum + ", "
				+ " brYear : " + brYear + ", "
				+ " brRdate : " + brRdate + ", "
				+ " brTypeQuick : " + brTypeQuick + ", "
				+ " brTypeSecret : " + brTypeSecret + ", "
				+ " brPlace : " + brPlace + ", "
				+ " brDate : " + brDate + ", "
				+ " brFrom : " + brFrom + ", "
				+ " brTo : " + brTo + ", "
				+ " brSubject : " + brSubject + ", "
				+ " brRemark : " + brRemark + ", "
				+ " brDivision : " + brDivision + ", "
				+ " brPcode : " + brPcode + ", "
				+ " brStatus : " + brStatus + ", "
				+ " brImage : " + brImage + ", ";
		return str;
	}
	
	public BookReciveOut(Integer brYear, Date brRdate, Integer brNum,
			String brPlace, Date brDate, String brFrom, String brTo,
			String brSubject, String brRemark) {
		this.brNum = brNum;
		this.brYear = brYear;
		this.brRdate = brRdate;
		this.brPlace = brPlace;
		this.brDate = brDate;
		this.brFrom = brFrom;
		this.brTo = brTo;
		this.brSubject = brSubject;
		this.brRemark = brRemark;
	}
	
	public BookReciveOut(Integer brNum, Integer brYear, Date brRdate,
			Integer brTypeQuick, Integer brTypeSecret, String field1,
			String brPlace, Date brDate, String brFrom, String brTo,
			String brSubject, String brRemark, String brDivision,
			String brPcode, String brStatus, String brImage) {
		this.brNum = brNum;
		this.brYear = brYear;
		this.brRdate = brRdate;
		this.brTypeQuick = brTypeQuick;
		this.brTypeSecret = brTypeSecret;
		this.brPlace = brPlace;
		this.brDate = brDate;
		this.brFrom = brFrom;
		this.brTo = brTo;
		this.brSubject = brSubject;
		this.brRemark = brRemark;
		this.brDivision = brDivision;
		this.brPcode = brPcode;
		this.brStatus = brStatus;
		this.brImage = brImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BR_ID", unique = true, nullable = false)
	public Integer getBrId() {
		return this.brId;
	}

	public void setBrId(Integer brId) {
		this.brId = brId;
	}

	@Column(name = "BR_NUM")
	public Integer getBrNum() {
		return this.brNum;
	}

	public void setBrNum(Integer brNum) {
		this.brNum = brNum;
	}

	@Column(name = "BR_YEAR")
	public Integer getBrYear() {
		return this.brYear;
	}

	public void setBrYear(Integer brYear) {
		this.brYear = brYear;
	}

	@Column(name = "BR_RDATE")
	public Date getBrRdate() {
		return this.brRdate;
	}

	public void setBrRdate(Date brRdate) {
		this.brRdate = brRdate;
	}

	@Column(name = "BR_TYPE_QUICK", length = 2)
	public Integer getBrTypeQuick() {
		return this.brTypeQuick;
	}

	public void setBrTypeQuick(Integer brTypeQuick) {
		this.brTypeQuick = brTypeQuick;
	}

	@Column(name = "BR_TYPE_SECRET", length = 2)
	public Integer getBrTypeSecret() {
		return this.brTypeSecret;
	}

	public void setBrTypeSecret(Integer brTypeSecret) {
		this.brTypeSecret = brTypeSecret;
	}

	@Column(name = "BR_PLACE", length = 50)
	public String getBrPlace() {
		return this.brPlace;
	}

	public void setBrPlace(String brPlace) {
		this.brPlace = brPlace;
	}

	@Column(name = "BR_DATE")
	public Date getBrDate() {
		return this.brDate;
	}

	public void setBrDate(Date brDate) {
		this.brDate = brDate;
	}

	@Column(name = "BR_FROM", length = 100)
	public String getBrFrom() {
		return this.brFrom;
	}

	public void setBrFrom(String brFrom) {
		this.brFrom = brFrom;
	}

	@Column(name = "BR_TO", length = 100)
	public String getBrTo() {
		return this.brTo;
	}

	public void setBrTo(String brTo) {
		this.brTo = brTo;
	}

	@Column(name = "BR_SUBJECT")
	public String getBrSubject() {
		return this.brSubject;
	}

	public void setBrSubject(String brSubject) {
		this.brSubject = brSubject;
	}

	@Column(name = "BR_REMARK")
	public String getBrRemark() {
		return this.brRemark;
	}

	public void setBrRemark(String brRemark) {
		this.brRemark = brRemark;
	}

	@Column(name = "BR_DIVISION", length = 50)
	public String getBrDivision() {
		return this.brDivision;
	}

	public void setBrDivision(String brDivision) {
		this.brDivision = brDivision;
	}

	@Column(name = "BR_PCODE", length = 13)
	public String getBrPcode() {
		return this.brPcode;
	}

	public void setBrPcode(String brPcode) {
		this.brPcode = brPcode;
	}

	@Column(name = "BR_STATUS", length = 1)
	public String getBrStatus() {
		return this.brStatus;
	}

	public void setBrStatus(String brStatus) {
		this.brStatus = brStatus;
	}

	@Column(name = "BR_IMAGE")
	public String getBrImage() {
		return this.brImage;
	}

	public void setBrImage(String brImage) {
		this.brImage = brImage;
	}

	/*//@ManyToOne(fetch = FetchType.LAZY)
   // @JoinColumn(name = "BR_TYPE_QUICK", insertable=false, updatable=false)
	public Integer getTypeQuick() {
		return typeQuick;
	}

	public void setTypeQuick(Integer typeQuick) {
		this.typeQuick = typeQuick;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
    //@JoinColumn(name = "BR_TYPE_SECRET", insertable=false, updatable=false)
	public Integer getTypeSecret() {
		return typeSecret;
	}

	public void setTypeSecret(Integer typeSecret) {
		this.typeSecret = typeSecret;
	}*/

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DIVISION")
	public String getDivision() {
		return division;
	}

	public void setDivision(String division) {
		this.division = division;
	}
	
	@Column(name = "UPDATED_BY")
	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
}
