package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookSendOut generated by hbm2java
 */
@Entity
@Table(name = "book_send_out", catalog = "document")
public class BookSendOut implements java.io.Serializable {

	private static final long serialVersionUID = -2935648839076161772L;
	private Integer bsId;
	private Integer bsNum;
	private Integer bsTypeQuick;
	private Integer bsTypeSecret;
	private Integer bsYear;
	private Date bsRdate;
	private String bsPlace;
	private Date bsDate;
	private String bsFrom;
	private String bsTo;
	private String bsSubject;
	private String bsRemark;
	private String bsDivision;
	private String bsPcode;
	private String bsStatus;
	private String bsImage;
	/*private Integer typeQuick;
	private Integer typeSecret;*/
	private String createdBy;
	private Date createdDate;
	private String division;
	private String updatedBy;
	private Date updatedDate;
	
	public BookSendOut() {
	}

	public BookSendOut(Integer bsYear, Date bsRdate, Integer bsNum,
			String bsPlace, Date bsDate, String bsFrom, String bsTo,
			String bsSubject, String bsRemark) {
		this.bsNum = bsNum;
		this.bsYear = bsYear;
		this.bsRdate = bsRdate;
		this.bsPlace = bsPlace;
		this.bsDate = bsDate;
		this.bsFrom = bsFrom;
		this.bsTo = bsTo;
		this.bsSubject = bsSubject;
		this.bsRemark = bsRemark;
	}
	
	public BookSendOut(Integer bsNum, Integer bsTypeQuick, Integer bsTypeSecret,
			Integer bsYear, Date bsRdate, String bsPlace, Date bsDate,
			String bsFrom, String bsTo, String bsSubject, String bsRemark,
			String bsDivision, String bsPcode, String bsStatus, String bsImage) {
		this.bsNum = bsNum;
		this.bsTypeQuick = bsTypeQuick;
		this.bsTypeSecret = bsTypeSecret;
		this.bsYear = bsYear;
		this.bsRdate = bsRdate;
		this.bsPlace = bsPlace;
		this.bsDate = bsDate;
		this.bsFrom = bsFrom;
		this.bsTo = bsTo;
		this.bsSubject = bsSubject;
		this.bsRemark = bsRemark;
		this.bsDivision = bsDivision;
		this.bsPcode = bsPcode;
		this.bsStatus = bsStatus;
		this.bsImage = bsImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BS_ID", unique = true, nullable = false)
	public Integer getBsId() {
		return this.bsId;
	}

	public void setBsId(Integer bsId) {
		this.bsId = bsId;
	}

	@Column(name = "BS_NUM")
	public Integer getBsNum() {
		return this.bsNum;
	}

	public void setBsNum(Integer bsNum) {
		this.bsNum = bsNum;
	}

	@Column(name = "BS_TYPE_QUICK")
	public Integer getBsTypeQuick() {
		return this.bsTypeQuick;
	}

	public void setBsTypeQuick(Integer bsTypeQuick) {
		this.bsTypeQuick = bsTypeQuick;
	}

	@Column(name = "BS_TYPE_SECRET")
	public Integer getBsTypeSecret() {
		return this.bsTypeSecret;
	}

	public void setBsTypeSecret(Integer bsTypeSecret) {
		this.bsTypeSecret = bsTypeSecret;
	}

	@Column(name = "BS_YEAR")
	public Integer getBsYear() {
		return this.bsYear;
	}

	public void setBsYear(Integer bsYear) {
		this.bsYear = bsYear;
	}

	@Column(name = "BS_RDATE")
	public Date getBsRdate() {
		return this.bsRdate;
	}

	public void setBsRdate(Date bsRdate) {
		this.bsRdate = bsRdate;
	}

	@Column(name = "BS_PLACE", length = 50)
	public String getBsPlace() {
		return this.bsPlace;
	}

	public void setBsPlace(String bsPlace) {
		this.bsPlace = bsPlace;
	}

	@Column(name = "BS_DATE")
	public Date getBsDate() {
		return this.bsDate;
	}

	public void setBsDate(Date bsDate) {
		this.bsDate = bsDate;
	}

	@Column(name = "BS_FROM", length = 50)
	public String getBsFrom() {
		return this.bsFrom;
	}

	public void setBsFrom(String bsFrom) {
		this.bsFrom = bsFrom;
	}

	@Column(name = "BS_TO")
	public String getBsTo() {
		return this.bsTo;
	}

	public void setBsTo(String bsTo) {
		this.bsTo = bsTo;
	}

	@Column(name = "BS_SUBJECT")
	public String getBsSubject() {
		return this.bsSubject;
	}

	public void setBsSubject(String bsSubject) {
		this.bsSubject = bsSubject;
	}

	@Column(name = "BS_REMARK", length = 100)
	public String getBsRemark() {
		return this.bsRemark;
	}

	public void setBsRemark(String bsRemark) {
		this.bsRemark = bsRemark;
	}

	@Column(name = "BS_DIVISION", length = 4)
	public String getBsDivision() {
		return this.bsDivision;
	}

	public void setBsDivision(String bsDivision) {
		this.bsDivision = bsDivision;
	}

	@Column(name = "BS_PCODE", length = 13)
	public String getBsPcode() {
		return this.bsPcode;
	}

	public void setBsPcode(String bsPcode) {
		this.bsPcode = bsPcode;
	}

	@Column(name = "BS_STATUS", length = 1)
	public String getBsStatus() {
		return this.bsStatus;
	}

	public void setBsStatus(String bsStatus) {
		this.bsStatus = bsStatus;
	}

	@Column(name = "BS_IMAGE")
	public String getBsImage() {
		return this.bsImage;
	}

	public void setBsImage(String bsImage) {
		this.bsImage = bsImage;
	}
/*	
	//@ManyToOne(fetch = FetchType.LAZY)
    //@JoinColumn(name = "BS_TYPE_QUICK", insertable=false, updatable=false)
	public Integer getTypeQuick() {
		return typeQuick;
	}

	public void setTypeQuick(Integer typeQuick) {
		this.typeQuick = typeQuick;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
    //@JoinColumn(name = "BS_TYPE_SECRET", insertable=false, updatable=false)
	public Integer getTypeSecret() {
		return typeSecret;
	}

	public void setTypeSecret(Integer typeSecret) {
		this.typeSecret = typeSecret;
	}*/

	@Column(name = "CREATED_BY")
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DIVISION")
	public String getDivision() {
		return division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "UPDATED_BY")
	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UPDATED_DATE")
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
