package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookReciveOut generated by hbm2java
 */
@Entity
@Table(name = "book_recive_out", catalog = "document")
public class BookReciveOut implements java.io.Serializable {

	private static final long serialVersionUID = -7691383831281035458L;
	private Integer brId;
	private String brNum;
	private Integer brYear;
	private String brRdate;
	private String brTypeQuick;
	private String brTypeSecret;
	private String field1;
	private String brPlace;
	private String brDate;
	private String brFrom;
	private String brTo;
	private String brSubject;
	private String brRemark;
	private String brDivision;
	private String brPcode;
	private String brStatus;
	private String brImage;

	public BookReciveOut() {
	}

	public BookReciveOut(Integer brYear, String brRdate, String brNum,
			String brPlace, String brDate, String brFrom, String brTo,
			String brSubject, String brRemark) {
		this.brNum = brNum;
		this.brYear = brYear;
		this.brRdate = brRdate;
		this.brPlace = brPlace;
		this.brDate = brDate;
		this.brFrom = brFrom;
		this.brTo = brTo;
		this.brSubject = brSubject;
		this.brRemark = brRemark;
	}
	
	public BookReciveOut(String brNum, Integer brYear, String brRdate,
			String brTypeQuick, String brTypeSecret, String field1,
			String brPlace, String brDate, String brFrom, String brTo,
			String brSubject, String brRemark, String brDivision,
			String brPcode, String brStatus, String brImage) {
		this.brNum = brNum;
		this.brYear = brYear;
		this.brRdate = brRdate;
		this.brTypeQuick = brTypeQuick;
		this.brTypeSecret = brTypeSecret;
		this.field1 = field1;
		this.brPlace = brPlace;
		this.brDate = brDate;
		this.brFrom = brFrom;
		this.brTo = brTo;
		this.brSubject = brSubject;
		this.brRemark = brRemark;
		this.brDivision = brDivision;
		this.brPcode = brPcode;
		this.brStatus = brStatus;
		this.brImage = brImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BR_ID", unique = true, nullable = false)
	public Integer getBrId() {
		return this.brId;
	}

	public void setBrId(Integer brId) {
		this.brId = brId;
	}

	@Column(name = "BR_NUM", length = 50)
	public String getBrNum() {
		return this.brNum;
	}

	public void setBrNum(String brNum) {
		this.brNum = brNum;
	}

	@Column(name = "BR_YEAR")
	public Integer getBrYear() {
		return this.brYear;
	}

	public void setBrYear(Integer brYear) {
		this.brYear = brYear;
	}

	@Column(name = "BR_RDATE", length = 10)
	public String getBrRdate() {
		return this.brRdate;
	}

	public void setBrRdate(String brRdate) {
		this.brRdate = brRdate;
	}

	@Column(name = "BR_TYPE_QUICK", length = 2)
	public String getBrTypeQuick() {
		return this.brTypeQuick;
	}

	public void setBrTypeQuick(String brTypeQuick) {
		this.brTypeQuick = brTypeQuick;
	}

	@Column(name = "BR_TYPE_SECRET", length = 2)
	public String getBrTypeSecret() {
		return this.brTypeSecret;
	}

	public void setBrTypeSecret(String brTypeSecret) {
		this.brTypeSecret = brTypeSecret;
	}

	@Column(name = "Field1", length = 50)
	public String getField1() {
		return this.field1;
	}

	public void setField1(String field1) {
		this.field1 = field1;
	}

	@Column(name = "BR_PLACE", length = 50)
	public String getBrPlace() {
		return this.brPlace;
	}

	public void setBrPlace(String brPlace) {
		this.brPlace = brPlace;
	}

	@Column(name = "BR_DATE", length = 10)
	public String getBrDate() {
		return this.brDate;
	}

	public void setBrDate(String brDate) {
		this.brDate = brDate;
	}

	@Column(name = "BR_FROM", length = 100)
	public String getBrFrom() {
		return this.brFrom;
	}

	public void setBrFrom(String brFrom) {
		this.brFrom = brFrom;
	}

	@Column(name = "BR_TO", length = 100)
	public String getBrTo() {
		return this.brTo;
	}

	public void setBrTo(String brTo) {
		this.brTo = brTo;
	}

	@Column(name = "BR_SUBJECT")
	public String getBrSubject() {
		return this.brSubject;
	}

	public void setBrSubject(String brSubject) {
		this.brSubject = brSubject;
	}

	@Column(name = "BR_REMARK")
	public String getBrRemark() {
		return this.brRemark;
	}

	public void setBrRemark(String brRemark) {
		this.brRemark = brRemark;
	}

	@Column(name = "BR_DIVISION", length = 50)
	public String getBrDivision() {
		return this.brDivision;
	}

	public void setBrDivision(String brDivision) {
		this.brDivision = brDivision;
	}

	@Column(name = "BR_PCODE", length = 13)
	public String getBrPcode() {
		return this.brPcode;
	}

	public void setBrPcode(String brPcode) {
		this.brPcode = brPcode;
	}

	@Column(name = "BR_STATUS", length = 1)
	public String getBrStatus() {
		return this.brStatus;
	}

	public void setBrStatus(String brStatus) {
		this.brStatus = brStatus;
	}

	@Column(name = "BR_IMAGE")
	public String getBrImage() {
		return this.brImage;
	}

	public void setBrImage(String brImage) {
		this.brImage = brImage;
	}

}
