package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookSendOut generated by hbm2java
 */
@Entity
@Table(name = "book_send_out", catalog = "document")
public class BookSendOut implements java.io.Serializable {

	private static final long serialVersionUID = -2935648839076161772L;
	private Integer bsId;
	private String bsNum;
	private String bsTypeQuick;
	private String bsTypeSecret;
	private Integer bsYear;
	private String bsRdate;
	private String bsPlace;
	private String bsDate;
	private String bsFrom;
	private String bsTo;
	private String bsSubject;
	private String bsRemark;
	private String bsDivision;
	private String bsPcode;
	private String bsStatus;
	private String bsImage;

	public BookSendOut() {
	}

	public BookSendOut(Integer bsYear, String bsRdate, String bsNum,
			String bsPlace, String bsDate, String bsFrom, String bsTo,
			String bsSubject, String bsRemark) {
		this.bsNum = bsNum;
		this.bsYear = bsYear;
		this.bsRdate = bsRdate;
		this.bsPlace = bsPlace;
		this.bsDate = bsDate;
		this.bsFrom = bsFrom;
		this.bsTo = bsTo;
		this.bsSubject = bsSubject;
		this.bsRemark = bsRemark;
	}
	
	public BookSendOut(String bsNum, String bsTypeQuick, String bsTypeSecret,
			Integer bsYear, String bsRdate, String bsPlace, String bsDate,
			String bsFrom, String bsTo, String bsSubject, String bsRemark,
			String bsDivision, String bsPcode, String bsStatus, String bsImage) {
		this.bsNum = bsNum;
		this.bsTypeQuick = bsTypeQuick;
		this.bsTypeSecret = bsTypeSecret;
		this.bsYear = bsYear;
		this.bsRdate = bsRdate;
		this.bsPlace = bsPlace;
		this.bsDate = bsDate;
		this.bsFrom = bsFrom;
		this.bsTo = bsTo;
		this.bsSubject = bsSubject;
		this.bsRemark = bsRemark;
		this.bsDivision = bsDivision;
		this.bsPcode = bsPcode;
		this.bsStatus = bsStatus;
		this.bsImage = bsImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BS_ID", unique = true, nullable = false)
	public Integer getBsId() {
		return this.bsId;
	}

	public void setBsId(Integer bsId) {
		this.bsId = bsId;
	}

	@Column(name = "BS_NUM", length = 50)
	public String getBsNum() {
		return this.bsNum;
	}

	public void setBsNum(String bsNum) {
		this.bsNum = bsNum;
	}

	@Column(name = "BS_TYPE_QUICK", length = 2)
	public String getBsTypeQuick() {
		return this.bsTypeQuick;
	}

	public void setBsTypeQuick(String bsTypeQuick) {
		this.bsTypeQuick = bsTypeQuick;
	}

	@Column(name = "BS_TYPE_SECRET", length = 2)
	public String getBsTypeSecret() {
		return this.bsTypeSecret;
	}

	public void setBsTypeSecret(String bsTypeSecret) {
		this.bsTypeSecret = bsTypeSecret;
	}

	@Column(name = "BS_YEAR")
	public Integer getBsYear() {
		return this.bsYear;
	}

	public void setBsYear(Integer bsYear) {
		this.bsYear = bsYear;
	}

	@Column(name = "BS_RDATE", length = 10)
	public String getBsRdate() {
		return this.bsRdate;
	}

	public void setBsRdate(String bsRdate) {
		this.bsRdate = bsRdate;
	}

	@Column(name = "BS_PLACE", length = 50)
	public String getBsPlace() {
		return this.bsPlace;
	}

	public void setBsPlace(String bsPlace) {
		this.bsPlace = bsPlace;
	}

	@Column(name = "BS_DATE", length = 10)
	public String getBsDate() {
		return this.bsDate;
	}

	public void setBsDate(String bsDate) {
		this.bsDate = bsDate;
	}

	@Column(name = "BS_FROM", length = 50)
	public String getBsFrom() {
		return this.bsFrom;
	}

	public void setBsFrom(String bsFrom) {
		this.bsFrom = bsFrom;
	}

	@Column(name = "BS_TO")
	public String getBsTo() {
		return this.bsTo;
	}

	public void setBsTo(String bsTo) {
		this.bsTo = bsTo;
	}

	@Column(name = "BS_SUBJECT")
	public String getBsSubject() {
		return this.bsSubject;
	}

	public void setBsSubject(String bsSubject) {
		this.bsSubject = bsSubject;
	}

	@Column(name = "BS_REMARK", length = 100)
	public String getBsRemark() {
		return this.bsRemark;
	}

	public void setBsRemark(String bsRemark) {
		this.bsRemark = bsRemark;
	}

	@Column(name = "BS_DIVISION", length = 4)
	public String getBsDivision() {
		return this.bsDivision;
	}

	public void setBsDivision(String bsDivision) {
		this.bsDivision = bsDivision;
	}

	@Column(name = "BS_PCODE", length = 13)
	public String getBsPcode() {
		return this.bsPcode;
	}

	public void setBsPcode(String bsPcode) {
		this.bsPcode = bsPcode;
	}

	@Column(name = "BS_STATUS", length = 1)
	public String getBsStatus() {
		return this.bsStatus;
	}

	public void setBsStatus(String bsStatus) {
		this.bsStatus = bsStatus;
	}

	@Column(name = "BS_IMAGE")
	public String getBsImage() {
		return this.bsImage;
	}

	public void setBsImage(String bsImage) {
		this.bsImage = bsImage;
	}

}
