package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Divisions generated by hbm2java
 */
@Entity
@Table(name = "divisions", catalog = "document")
public class Divisions implements java.io.Serializable {

	private static final long serialVersionUID = 7700831413351122353L;
	private Integer id;
	private String divisionCode;
	private String divisionShort;
	private String divisionName;
	private String organization;

	public Divisions() {
	}

	public Divisions(String divisionCode) {
		this.divisionCode = divisionCode;
	}

	public Divisions(String divisionCode, String divisionShort,
			String divisionName, String organization) {
		this.divisionCode = divisionCode;
		this.divisionShort = divisionShort;
		this.divisionName = divisionName;
		this.organization = organization;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "division_code", nullable = false, length = 4)
	public String getDivisionCode() {
		return this.divisionCode;
	}

	public void setDivisionCode(String divisionCode) {
		this.divisionCode = divisionCode;
	}

	@Column(name = "division_short", length = 10)
	public String getDivisionShort() {
		return this.divisionShort;
	}

	public void setDivisionShort(String divisionShort) {
		this.divisionShort = divisionShort;
	}

	@Column(name = "division_name")
	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

	@Column(name = "organization", length = 100)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

}
