package com.java.doc.model;

// Generated Apr 20, 2015 2:42:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeQuick generated by hbm2java
 */
@Entity
@Table(name = "type_quick", catalog = "document")
public class TypeQuick implements java.io.Serializable {

	private static final long serialVersionUID = 3875134034517921107L;
	private Integer id;
	private String typeQuick;
	private String active;

	public TypeQuick() {
	}

	public TypeQuick(String typeQuick, String active) {
		this.typeQuick = typeQuick;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TYPE_QUICK", length = 100)
	public String getTypeQuick() {
		return this.typeQuick;
	}

	public void setTypeQuick(String typeQuick) {
		this.typeQuick = typeQuick;
	}

	@Column(name = "ACTIVE", length = 1)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
